#!/bin/sh

exists() {
	which "$1" >/dev/null 2>&1
}

TESTER=nosetests-3.4
exists $TESTER || TESTER=nosetests3
exists $TESTER || TESTER=nosetests

case $(pwd) in
	*/test/unittests)
		PYTHONPATH=../.. $TESTER -w . "$@"
		;;
	*/test)
		PYTHONPATH=.. $TESTER -w unittests "$@"
		;;
	*)
		PYTHONPATH=. $TESTER -w test/unittests "$@"
		;;
esac

