---
sudo: false
language: python
python:
  - "3.4.1"
  - "3.5"
install:
  - "pip install -r requirements.txt"
script: ./test/run --with-coverage
notifications:
  irc: "chat.freenode.net#clusterlabs-dev"
